### ISSUE TITLE
[gdi - frontend] improve backend error handling and displaying

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-frontend#202]
### 🎯 What? (Story Description)

We need to present error response detail and errorMessages retrieved by the backend.

### 💡 Why? (Justification)

To improve user experience.

### 🔨 Tasks (Breakdown)

- Implement error handling and displaying of API backend 4xx and 5xx error detail and error messages. It should be generic for the entire app.
- Add and improve tests when needed.

### ✅ Acceptance Criteria

- Do I see 4xx or 5xx error detail and error messages from backend?

### ➕ Additional Information

`ErrorResponse` schema:
```yaml
ErrorResponse:
  properties:
    title:
      type: string
      title: Error title
    status:
      type: integer
      title: Error status
    detail:
      type: string
      title: Error detail
    errorMessages:
      type: array
      items:
        type: string
      description: Additional error messages related to the response
```
